<?php

namespace Test\Ease\ui;

use Ease\ui\MainPageMenu;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-12-20 at 17:21:58.
 */
class MainPageMenuTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MainPageMenu
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MainPageMenu();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ease\ui\MainPageMenu::addMenuItem
     */
    public function testAddMenuItem()
    {
        $this->object->addMenuItem('https://www.vitexsoftware.cz/img/ease-framework-logo.png', 'Ease Framework', 'https://www.vitexsoftware.cz/ease.php');
    }

    /**
     * @covers Ease\ui\MainPageMenu::finalize
     */
    public function testFinalize()
    {
        $this->object->finalize();
    }
}
