<?php

namespace Test\Ease\ui;

use Ease\ui\SemaforLight;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-12-23 at 02:03:16.
 */
class SemaforLightTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SemaforLight
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SemaforLight();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ease\ui\SemaforLight::colorNameToHex
     */
    public function testColorNameToHex()
    {
        $this->assertEquals('#556B2F',
            SemaforLight::colorNameToHex('darkolivegreen'));
    }

    /**
     * @covers \Ease\ui\SemaforLight::getColorCode
     */
    public function testGetColorCode()
    {
        $this->assertEquals('#f0ad4e', $this->object->getColorCode('warning'));
        $this->assertEquals('#0000FF', $this->object->getColorCode('blue'));
    }

    /**
     * @covers \Ease\ui\SemaforLight::adjustBrightness
     */
    public function testAdjustBrightness()
    {
        $this->assertEquals('#ffff7b',
            SemaforLight::adjustBrightness('#ffbf00', 123));
    }
}
