<?php

namespace Test\Ease\ui;

use Ease\ui\TWBSwitch;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-11 at 19:37:36.
 */
class TWBSwitchTest extends \PHPUnit_Framework_TestCase  // \Test\Ease\Html\CheckboxTagTest
{
    /**
     * @var TWBSwitch
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TWBSwitch('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ease\ui\TWBSwitch::setProperties
     */
    public function testSetProperties()
    {
        $this->object->setProperties(['test' => true]);
    }

    /**
     * @covers Ease\ui\TWBSwitch::finalize
     */
    public function testFinalize()
    {
        $this->object->finalize();
    }
}
