<?php

namespace Test\Ease\ui;

use Ease\ui\TWBTreeView;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-06-20 at 15:41:12.
 */
class TWBTreeViewTest extends\PHPUnit_Framework_TestCase  //  \Test\Ease\Html\TagTest
{
    /**
     * @var TWBTreeView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TWBTreeView('test', []);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ease\ui\TWBTreeView::finalize
     * @todo   Implement testFinalize().
     */
    public function testFinalize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
